import React, { useState } from 'react';
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

interface QandAProps {
  documentId: string;
}

const QandA: React.FC<QandAProps> = ({ documentId }) => {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');

  const handleAskQuestion = () => {
    // In a real app, you would send the question and documentId to your backend API.
    console.log(`Asking question: "${question}" for document: ${documentId}`);
    // Mock answer
    setAnswer(`This is a sample answer for the question: "${question}". In a real application, this would be generated by an AI model based on the document content.`);
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Ask a Question</CardTitle>
        <CardDescription>Ask a question about the uploaded document.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex w-full items-center space-x-2">
          <Input type="text" placeholder="e.g., What is the main topic?" value={question} onChange={(e) => setQuestion(e.target.value)} />
          <Button onClick={handleAskQuestion} disabled={!question}>Ask</Button>
        </div>
        {answer && <div className="p-4 bg-gray-100 dark:bg-gray-800 rounded-md"><p className="text-gray-800 dark:text-gray-200">{answer}</p></div>}
      </CardContent>
    </Card>
  );
};

export default QandA;